name: GitHub Actions Demo

on:
  push:
    branches: [ main ]
    paths-ignore: [.github/**]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs:
  Build:
    name: Bild
    runs-on: ubuntu-latest
    steps:
      - name: Outputu envs
        run: |
          echo "${{ github.event.action }}"
          echo "${{ github.base_ref }}"
        
      - uses: actions/checkout@v3

      - name: List file
        run: |
          tree
