name: GitHub Actions Demo

on:
  push:
    branches: [ main ]
    paths-ignore: [.github/**]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Outputu envs
        run: |
          echo "${{ github.event.action }}"
          echo "${{ github.base_ref }}"
        
      - uses: actions/checkout@v3

      - name: List file
        run: |
          tree

  Test:
    runs-on: ubuntu-latest
    environment: Test
    needs: Build
    steps:
      - run: echo "Testing"
  Load-Test:
    runs-on: ubuntu-latest
    environment: Load-Test
    needs: Build
    steps:
      - run: echo "Load Testing"

  Production:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://writeabout.net
    if: github.event.inputs.environment == 'Production'
    needs: ["Test","Load-test"]
    steps:
      - run: echo "Load Testing"
