name: Reusable workflow

on:
  workflow_dispatch:
    inputs:
      who-to-greet:
        type: string
    outputs:
      current-time:
        value: ${{ jobs.reusable-job.outputs.current-time }}


jobs:
  reusable-job:
    outputs:
      current-time: ${{ steps.time.outputs.time}}
    runs-on: "ubuntu-latest"
    steps:
      - run: echo "Hello ${{ inputs.who-to-greet }}" 

      - name: time
        id: time
        run: echo "current-time=$(date)" >> $GITHUB_OUTPUT"
